INSERT INTO [dbo].[Filmes] ([id_filme], [nome_filme], [genero], [duracao]) VALUES (1, N'Guardiões da Galáxia 2', 4, N'02:00:00')
INSERT INTO [dbo].[Filmes] ([id_filme], [nome_filme], [genero], [duracao]) VALUES (2, N'Amarelinho', 8, N'02:00:00')
INSERT INTO [dbo].[Filmes] ([id_filme], [nome_filme], [genero], [duracao]) VALUES (3, N'Call Girl', 3, N'02:00:00')
INSERT INTO [dbo].[Filmes] ([id_filme], [nome_filme], [genero], [duracao]) VALUES (4, N'Foge', 6, N'02:00:00')
INSERT INTO [dbo].[Filmes] ([id_filme], [nome_filme], [genero], [duracao]) VALUES (5, N'The Boss Baby', 8, N'02:00:00')
INSERT INTO [dbo].[Filmes] ([id_filme], [nome_filme], [genero], [duracao]) VALUES (6, N'Velocidade Furiosa 8', 1, N'02:00:00')
INSERT INTO [dbo].[Filmes] ([id_filme], [nome_filme], [genero], [duracao]) VALUES (7, N'Sacanas Sem Lei', 1, N'02:00:00')
INSERT INTO [dbo].[Filmes] ([id_filme], [nome_filme], [genero], [duracao]) VALUES (8, N'Mulher Maravilha', 1, N'02:00:00')
INSERT INTO [dbo].[Filmes] ([id_filme], [nome_filme], [genero], [duracao]) VALUES (9, N'Interstellar', 4, N'02:00:00')
INSERT INTO [dbo].[Filmes] ([id_filme], [nome_filme], [genero], [duracao]) VALUES (10, N'Perdidos', 3, N'02:00:00')
INSERT INTO [dbo].[Filmes] ([id_filme], [nome_filme], [genero], [duracao]) VALUES (11, N'Elementos Secretos', 3, N'02:00:00')
INSERT INTO [dbo].[Filmes] ([id_filme], [nome_filme], [genero], [duracao]) VALUES (12, N'As Cronicas de Nárnia', 4, N'02:00:00')
INSERT INTO [dbo].[Filmes] ([id_filme], [nome_filme], [genero], [duracao]) VALUES (13, N'The Hunger Games - A revolta - Parte 2', 7, N'02:00:00')
INSERT INTO [dbo].[Filmes] ([id_filme], [nome_filme], [genero], [duracao]) VALUES (14, N'Deadpool', 2, N'02:00:00')
