//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho_IS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmes_Sala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filmes_Sala()
        {
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int id_filme_sala { get; set; }
        public int id_filme { get; set; }
        public int id_sala { get; set; }
        public Nullable<System.DateTime> hora { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual Filmes Filmes { get; set; }
        public virtual Salas Salas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
