//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho_IS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int id_reserva { get; set; }
        public Nullable<int> id_filme_sala { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public Nullable<int> telefone { get; set; }
        public int referencia { get; set; }
        public int lugar { get; set; }
    
        public virtual Filmes_Sala Filmes_Sala { get; set; }
    }
}
